### ISSUE TITLE
Items to Include in Teacher Tips

### ISSUE THREAD

**Issue by arouinfar** [phetsims/states-of-matter#168]
From the Java Tips (some rewording necessary)
- [x]  For solid water, the sim simplifies the model emphasizing that there is space between the
  molecules. A resource for the most common visual for ice structure is
  http://www1.lsbu.ac.uk/water/hexagonal_ice.html
- [x] The phase diagrams are shown qualitatively in the sim, to help students get a general
  understanding of phase diagrams. Quantitative phase diagrams are shown for water, neon,
  argon and oxygen on page 2 of these Tips. (Elaborate on this to address https://github.com/phetsims/states-of-matter/issues/168#issuecomment-264053333.)
- [x] The sim is not designed to be used as a comprehensive tool for learning about phase
  diagrams, instead the focus is on phases of matter. The small number of particles shown and
  the simplicity of the underlying models makes it difficult to map accurately the exact phase to
  the correct regions of the phase diagram. However, we felt there would be some benefit to
  students being exposed to a simplified phase diagram. In the sim, the diagram marker remains
  on the coexistence line between liquid/gas or solid/gas (and is extrapolated into the critical
  region). If this approximation does not fit your specific learning goals, and you are concerned
  this might cause confusion, you can encourage your students to keep the phase diagram
  closed.

Additional model simplifications  
- [x] Pressure will be zero at 0K because zero motion = zero momentum transfers between the particles and the container walls = zero pressure #154 
- [x] It is possible to reach absolute zero, but the rate of temperature change slows down quite substantially as 0K is approached.  This is intentional, since it is very difficult to make a system of molecules this cold.  True absolute zero is impossible to achieve, so this should be thought of as rounding down from anything below 0.5K.
- [x] A note that we do not include Plasma on purpose (even though it is considered a state of matter). 
- [x] Some amount of gravity is simulated, but it is minimal - just enough to keep the solid forms of the substances on the floor of the container.  For this reason, substances in their liquid form don't always spread out along the bottom of the container, as, say, water does in a glass.
- [x] The model works best when there are at least (roughly) 15 particles in the container.  It is possible to create situations where there are only a few particles in the container and, in these situations, users may observe some odd behaviors.  One example is occasional visible changes to the velocity of individual particles.  If students observe such things, they should be told that this is a due to the limitations of the model, and doesn't represent "real world" phenomena.
- [x] Equilibrium states -- https://github.com/phetsims/states-of-matter/issues/168#issuecomment-264053333
- [ ] Limits of quantitative comparisons -- https://github.com/phetsims/states-of-matter/issues/168#issuecomment-264053333
- [x] Latent heat is not really being addressed (but could discuss the breaking of the crystal lattice order or such) -- https://github.com/phetsims/states-of-matter/issues/168#issuecomment-264054515
- [x] Temperature is allowed to change when particles are injected, based on the velocity of the particles -- #182 

Other things to note
- [x] Bicycle pump indicator bars #167
- [x] A bit of explanation of "Return Lid" behavior, might be useful since it might not be completely obvious. basically that it captures the particles in the container at the time and the pump is "refilled" to a level that allows the max number of particles (I believe)
- [x] For younger students, it may be important to explain that the hand and the container are not at all to scale, since in the real world they too are made of atoms and molecules.

**Comment by arouinfar** [comment]
@jbphet if there is anything else you can think of, please add them to the checklist.

**Comment by arouinfar** [comment]
Marking as on-hold until the sim is closer to publication.

**Comment by jbphet** [comment]
Here's an item:

[ ] - It is possible to reach absolute zero, but the rate of temperature change slows down quite substantially as 0K is approached.  This is intentional, since it is very difficult to make a system of molecules this cold.  True absolute zero is impossible to achieve, so this should be thought of as rounding down from anything below 0.5K.

**Comment by arouinfar** [comment]
@ariel-phet when you have some time, can you review this list and see if there's anything else that should be documented?

**Comment by ariel-phet** [comment]
@arouinfar two things:
- a bit of explanation of "Return Lid" behavior, might be useful since it might not be completely obvious. basically that it captures the particles in the container at the time and the pump is "refilled" to a level that allows the max number of particles (I believe)
- a note that we do not include Plasma on purpose (even though it is considered a state of matter). I have seen a few user comments about that in the past

**Comment by jbphet** [comment]
Two more thoughts:
- [ ] Some amount of gravity is simulated, but it is minimal - just enough to keep the solid forms of the substances on the floor of the container.  For this reason, substances in their liquid form don't always spread out along the bottom of the container, as, say, water does in a glass.
- [ ] For younger students, it may be important to explain that the hand and the container are not at all to scale, since in the real world they too are made of atoms and molecules.

**Comment by arouinfar** [comment]
Thanks @jbphet and @ariel-phet!

**Comment by jbphet** [comment]
Another thought:

- [ ] The model works best when there are at least (roughly) 15 particles in the container.  It is possible to create situations where there is only a few particles in the container and, in these situations, users may observe some odd behaviors.  One example is occasional visible changes to the velocity of individual particles.  If students observe such things, they should be told that this is a due to the limitations of the model, and doesn't represent "real world" phenomena.

**Comment by ariel-phet** [comment]
And here is a fun one for you @arouinfar, from unfuddle (2013), worth a read through and seeing if a few sentences would help with some of the concerns:

> Dear PhET,
> 
> A few weeks ago I had the pleasure of hearing a presentation on PhET from Emily Moore, who was visiting some of my colleagues here at Weber State University in Utah.  This motivated me to take a closer look at some of your simulations, and she invited me to submit feedback, so here we go.  I'll start with the States of Matter simulation and, I hope, follow-up with feedback on some of the others at a later date.
> 
> You've done a nice job in States of Matter with the visual elements and user controls.  I think this simulation succeeds in giving the user a mental image of what molecules are doing in solids, liquids, and gases.
> 
> But of course, I have some criticisms and suggestions.
> 
> First, the phase diagram has to be either fixed or eliminated.  I see that in the teacher's guide you acknowledge that it is a "simplified approximation," but those aren't the correct words.  The phase diagram is often flat-out wrong.  It is easy in this simulation to create states that do not lie on the phase equilibrium line, yet the diagram always shows them on the equilibrium line.  Pump some extra gas into the container and push the piston down until you have a pure liquid; you can get the pressure well above 100 atm.  Then blow the top off to let most of the material out, and replace the lid.  You now have a pure gas, perhaps at exactly the same temperature as the previous liquid, but at a pressure of only a couple of atm.  Yet the phase diagram shows these two states identically!  The diagram seems to totally ignore the measured pressure, so its vertical dimension is not actually being used.  Students who already understand xy plots will be horribly confused and start to question their understanding, while students who don't already understand xy plots will learn that these plots are not intended to be understood.
> 
> Second, it appears from using this simulation that it is intended only for studying equilibrium states (since the rates of adding energy, adding particles, and changing the volume are so limited).  I find this somewhat limiting but I can understand how you don't want to try to do too much in one simulation.  You might think about a future enhanced version that makes it easier to set up nonequilibrium states and watch them spontaneously evolve toward equilibrium.  But meanwhile, I'm perplexed that neither the page describing the simulation nor the pdf teachers guide mentions this restriction.  In fact, I can't find the word "equilibrium" anywhere at all.  It seems as if there is a tacit assumption that students and teachers are unaware, and are to be kept unaware, of the existence in nature of nonequilibrium states.  Yet nonequilibrium states are everywhere!  I'm not merely worried here about students being bewildered when they learn of the existence of superheated and supercooled water.  The misconception that everything is in equilibrium makes it impossible to understand just about any area of science, from cosmology to biology.  I think it would be easy to revise the documentation to raise this issue and, hence, lessen the chance of perpetuating this misconception.  Just highlight the fact that the three types of user inputs are kept slow so that the system can generally equilibrate as the changes are made--and that faster changes, if they were allowed, would produce a vastly greater variety of system states.
> 
> Third, I'm unclear on whether this simulation is intended to be used quantitatively.  Obviously it provides quantitative temperature and pressure measurements, but I don't know how seriously to take them.  Are these true (scaled) measurements of the properties of the depicted small-N molecular dynamics model, or are they taken from experiments on real substances and somehow fitted to the model's qualitative appearance after the fact?  Can I use them to make meaningful comparisons of the behavior of this system to that of an ideal gas?  I've tried doubling the temperature of a gas at constant volume and was pleased that the pressure *more* than doubled, as it should when there are attractive forces between molecules.  Still, the documentation doesn't discuss this kind of use, and I don't know how far it can be pushed.  A high school teacher, moreover, might not even have the expertise to recognize whether the simulation is giving reasonable results when used in such a way.
> 
> In general, I find this simulation to be inadequately documented.  This seems very odd, because I know how hard you've worked to design your simulations and test them out and refine them.  After all that hard work, why not be more explicit with the public about what the simulation is actually doing, what its limitations are, and how you intend it to be used?
> 
> Thanks for listening,
> 
> 
>

**Comment by ariel-phet** [comment]
And another...but basically the tips should probably include some comment in the model section about latent heat not really being addressed (but could discuss the breaking of the crystal lattice order or such)


> PheT developers,
> 
> I just want to give a heads up that there are some fundamental problems with your depiction of phase changes here: https://phet.colorado.edu/en/simulation/legacy/states-of-matter
> 
> For instance, none of the phase changes in the simulation require heat of transformation (latent heat). This is a major concern that prevents me from using this particular simulation in my classroom.
> 
> There are some other kinks to work out as well. If you are interested receiving feedback to make this simulation more accurately reflect the thermodynamics of phase changes, please let me know.

**Comment by arouinfar** [comment]
Thanks for finding this user emails @ariel-phet. I can certainly address these in the Tips, but will most likely need to pick @jbphet's brain about some of the model issues raised in https://github.com/phetsims/states-of-matter/issues/168#issuecomment-264053333.

**Comment by arouinfar** [comment]
I've uploaded the teacher tips for SOM and SOMB, but I haven't fully addressed https://github.com/phetsims/states-of-matter/issues/168#issuecomment-264053333. I will need to talk more with @jbphet about the model when I'm back in the office.
