### ISSUE TITLE
States of Matter Master Checklist

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/states-of-matter#175]
## Design
- [x] **Sim folder and design doc created** (Date: 05/22/2014) 
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- [x] **Legacy sim docs/info gathered**
- [x] **Learning goals and standards identified** (Date: 10/24/2014)
- [x] **Design concept complete**  (Date: 10/24/2014)
- [x] **Wireframes complete** (Date: 10/24/2014) 
- [x] **Mockups complete** (Date: 10/28/2014) 
  - [x] Mockups checked for colorblind and greyscale
- [x] **Interviews complete** (Date: 8/10/2016) 
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: 12/13/2016) 
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [x] **Pre-publication items** 
  - [x] Screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Guide
  - [x] Compatible activities ([author spreadsheet](https://docs.google.com/spreadsheets/d/1AOc1vy0HfEeJQ9sT0Vs_sr6dqmsEHfq7HWUBGQV_VQA/edit#gid=0))
  - [x] Sim primer (Being tracked in #203)
  - [x] Verify credits
- [x] **Update [Gooru PhET URL tracker](https://docs.google.com/spreadsheets/d/19sffdKj9NdMuFdp3NcFeJmPyDY-3KsoM7Pbu84gUVtw/edit#gid=636879231)**
- [x] **Add to Edmodo**

## Implementation
- [x] **Sim repo created** (Date: 10/15/2014) 
  - [x] Simula-rasa used to create basic project structure
  - [x] Grunt unpublished-readme run to create the initial readme file
  - [x] Collaborators added (such as QA team, designers, etc)
  - [x] Standard label set applied
  - [x] Sim added to active repos list in chipper
  - [x] Sim suggestions doc reviewed
  - [x] Unfuddle tickets reviewed
  - [x] Port existing strings (IF ANY) and commit to the GitHub repo (auto-ported strings from Java and Flash sims can be found in babel/autoport). The strings should be deleted from babel/autoport and @jbphet should immediately be asked to pull from rosetta to avoid conflicts.
- [x] **Initial development started** (Date: 12/01/2014)
- [x] **Sim feature complete** (Date: 05/18/2015) 
- [x] **Code review complete** (Date: 05/15/2015) 
  - [x] Code review checklist
  - [x] Model description 
- [x] **Published** (Date: 12/20/2016)
  - [x] Update repo README to published template

## QA
- [x] **Legacy sim tested for bugs**; issues reported in repo
- [x] **Dev testing complete** (Date: 11/30/2016) 
- [x] **First release candidate** (Date: 12/13/2016)
  - [x] Place in matrix in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
  - [x] Test matrix deemed complete

**Comment by ariel-phet** [comment]
@arouinfar and @jbphet remaining items for you here

**Comment by jbphet** [comment]
The readme has been updated, which I think was the last unchecked item for me.  Unassigning.
